module.exports = {
  FILE_SELECT_EMPTY_BUTTON: 'fileSelectEmptyButton',
  FILE_SELECT_BORDER_BUTTON: 'fileSelectBorderButton',
  EMPTY_IMAGE_OPENED: 'emptyImageOpened',
  BORDER_IMAGE_OPENED: 'borderImageOpened',

  TOP_LEFT_BORDER: 'topLeftBorder',
  LEFT_BORDER: 'leftBorder',
  BOTTOM_LEFT_BORDER: 'bottomLeftBorder',
  BOTTOM_BORDER: 'bottomBorder',
  BOTTOM_RIGHT_BORDER: 'bottomRightBorder',
  RIGHT_BORDER: 'rightBorder',
  TOP_RIGHT_BORDER: 'topRightBorder',
  TOP_BORDER: 'topBorder',

  //generated with generator.js
  BORDERS: [
    [true, true, true, true, true, true, true, true],
    [true, true, true, true, true, false, true, true],
    [true, false, true, true, true, false, true, true],
    [true, false, true, true, true, true, true, true],
    [true, true, true, false, true, false, true, true],
    [true, false, true, false, true, true, true, true],
    [true, true, true, false, true, false, true, false],
    [true, false, true, false, true, false, true, true],
    [true, false, true, false, true, false, false, false],
    [true, false, true, false, false, false, true, false],
    [false, false, false, false, true, false, true, false],
    [false, false, true, false, true, false, false, false],
    [true, true, true, false, true, true, true, true],
    [true, true, true, false, false, false, true, true],
    [true, false, false, false, false, false, true, true],
    [true, false, false, false, true, true, true, true],
    [true, true, true, true, true, false, true, false],
    [true, false, true, true, true, true, true, false],
    [true, false, true, true, true, false, true, false],
    [true, false, true, false, true, true, true, false],
    [false, false, true, false, true, false, true, false],
    [true, false, false, false, true, false, true, false],
    [true, false, false, false, false, false, true, false],
    [true, false, true, false, false, false, false, false],
    [true, true, true, false, true, true, true, false],
    [true, true, true, false, false, false, false, false],
    [false, false, false, false, false, false, false, false],
    [false, false, false, false, true, true, true, false],
    [true, true, true, false, false, false, true, false],
    [true, false, false, false, true, false, true, true],
    [true, true, true, false, true, false, false, false],
    [true, false, true, false, false, false, true, true],
    [false, false, false, false, true, false, false, false],
    [false, false, true, false, false, false, false, false],
    [true, false, false, false, true, false, false, false],
    [false, false, true, false, false, false, true, false],
    [true, true, true, true, true, true, true, false],
    [true, true, true, true, true, false, false, false],
    [false, false, true, true, true, false, false, false],
    [false, false, true, true, true, true, true, false],
    [true, false, true, true, true, false, false, false],
    [false, false, true, false, true, true, true, false],
    [false, false, true, true, true, false, true, false],
    [true, false, false, false, true, true, true, false],
    [false, false, false, false, false, false, true, false],
    [true, false, false, false, false, false, false, false],
    [true, false, true, false, true, false, true, false],
  ],
};
